#spring:
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/db_UserCRUD2408BApp?useSSL=false
#    username: root
#    password:
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          time_zone: Asia/Tokyo
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: update
#    show-sql: true
#server:
#    port: 9191